### ISSUE TITLE
test failing

### ISSUE THREAD

**Issue by albfan** [frenkhub/xml-sorter#5]
With custom order looks like other attributtes are sorted in reverse order:

This change make test suite to pass

```
diff --git i/test/core.sort.test.js w/test/core.sort.test.js
index 505518c..089063a 100644
--- i/test/core.sort.test.js
+++ w/test/core.sort.test.js
@@ -55,10 +55,10 @@ describe('xml-sort', function () {
             "<artist f=\"aaa\"/>" +
             "<artist f=\"bbb\"/>" +
             "<artist b=\"ccc\"/>" +
-            "<artist a=\"zzz\"/>" +
-            "<artist c=\"aaa\"/>" +
-            "<artist d=\"aaa\"/>" +
             "<artist e=\"aaa\"/>" +
+            "<artist d=\"aaa\"/>" +
+            "<artist c=\"aaa\"/>" +
+            "<artist a=\"zzz\"/>" +
             "</root>";
 
         var customComparator = Core.buildComparatorFromList(["f", "b"]);
```

I checked adding another property `<artist z=\"zzz\"/>` which is sorted as first after custom `f` and `b`

**Comment by frenkhub** [comment]
Thanks again, fixed!

**Comment by albfan** [comment]
@frenkhub I think the test was correct as it was. isn't it? 

why after custom order `f`, `b` you get `e` `d` `c` `a` atributtes? I suppose `a` `c` `d` `e` was the correct order (alphabetically)

**Comment by frenkhub** [comment]
Because `buildComparatorFromList` consider every string different from `f` and `b` equal. 

It is possible composing two comparators together with the compose function: it takes two comparators as arguments and if the first comparator returns 0 then the second comparator is used.

**Comment by albfan** [comment]
Hmm, probably that's the expected behaviour.

If I want to see `id` first still want the other attributes alphabetically ordered.

I can try to code a PR for that

**Comment by frenkhub** [comment]
Wait, if you are using the tool from command line this is the current behaviour. For example 'npx xml-sorter -a 'id name' file.xml' will sort tags with the same name and with the same parent in this way: 

1. first tags with the `id` attribute;
2. then tags with the `name` attribute;
3. then the other tags sorted alphabetically;

**Comment by albfan** [comment]
I reread test. It is sorting tags by attribute.

I confuse with sort attributes in a tag.

Still looks strange that same tags sorted by attribute names do not sort alphabetically after Custom order, but it's not 'per se' defined.

Maybe more than one tag without attribute f or b adds confussion here, as result is not defined, and there will be several correct results.

I think is better to remove those extra tags or define the result for the test, what do you think?

**Comment by frenkhub** [comment]
Yes, maybe it confused me too. I will edit the unit test and I remove the extra tags, I let just one extra tag 👍. Are you using this tool in your projects?

**Comment by albfan** [comment]
I'm trying to came up with a diff tool for complex xml, like bpmn, this would be used for a pre filter to sort before compare
